-- EventScape (serverless) schema
-- This schema is intentionally permissive for demo usage.
-- For production, enable strict RLS and use Supabase Auth.

create extension if not exists "pgcrypto";

create table if not exists public.roster (
  uid text primary key,
  name text not null,
  role text not null default 'student',
  team_name text references public.teams(name) on update cascade on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.teams (
  name text primary key,
  color text not null default '#3b7eff',
  invite_code text unique,
  leader_uid text,
  leader_name text,
  created_at timestamptz not null default now()
);

alter table public.teams add column if not exists invite_code text;
alter table public.teams add column if not exists leader_uid text;
alter table public.teams add column if not exists leader_name text;

update public.teams
set invite_code = upper(substr(md5(gen_random_uuid()::text), 1, 6))
where invite_code is null or length(invite_code) <> 6;

alter table public.teams alter column invite_code set not null;
create unique index if not exists teams_invite_code_idx on public.teams(invite_code);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'teams_invite_code_format_check'
      and conrelid = 'public.teams'::regclass
  ) then
    alter table public.teams
      add constraint teams_invite_code_format_check
      check (invite_code ~ '^[A-Z0-9]{6}$');
  end if;
end $$;

create or replace function public.prevent_team_code_update()
returns trigger
language plpgsql
as $$
begin
  if old.invite_code is distinct from new.invite_code then
    raise exception 'TEAM_CODE_IMMUTABLE';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_prevent_team_code_update on public.teams;
create trigger trg_prevent_team_code_update
before update on public.teams
for each row
execute function public.prevent_team_code_update();

create table if not exists public.team_memberships (
  id bigint generated by default as identity primary key,
  uid text not null,
  user_name text not null default '',
  team_name text not null references public.teams(name) on update cascade on delete cascade,
  is_leader boolean not null default false,
  created_at timestamptz not null default now(),
  unique(uid, team_name)
);

create index if not exists team_memberships_uid_idx on public.team_memberships(uid);
create index if not exists team_memberships_team_name_idx on public.team_memberships(team_name);

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  team_name text not null references public.teams(name) on update cascade on delete restrict,
  members text not null default '',
  type text not null default 'Convention',
  field text not null default '',
  loc text not null default '',
  lat double precision not null,
  lng double precision not null,
  topic text not null default '',
  description text not null default '',
  scale text not null default '',
  files jsonb not null default '[]'::jsonb,
  feedbacks jsonb not null default '[]'::jsonb,
  liked_by text[] not null default '{}'::text[],
  created_at timestamptz not null default now()
);

create index if not exists events_team_name_idx on public.events(team_name);
create index if not exists events_created_at_idx on public.events(created_at desc);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  room text not null,
  sender_id text,
  sender_name text not null,
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists messages_room_created_at_idx on public.messages(room, created_at);

-- RLS (demo-friendly)
alter table public.roster enable row level security;
alter table public.teams enable row level security;
alter table public.team_memberships enable row level security;
alter table public.events enable row level security;
alter table public.messages enable row level security;

drop policy if exists "roster_read_all" on public.roster;
create policy "roster_read_all" on public.roster for select using (true);
drop policy if exists "roster_write_all" on public.roster;
create policy "roster_write_all" on public.roster for insert with check (true);
drop policy if exists "roster_update_all" on public.roster;
create policy "roster_update_all" on public.roster for update using (true) with check (true);

drop policy if exists "teams_read_all" on public.teams;
create policy "teams_read_all" on public.teams for select using (true);
drop policy if exists "teams_write_all" on public.teams;
create policy "teams_write_all" on public.teams for insert with check (true);
drop policy if exists "teams_update_all" on public.teams;
create policy "teams_update_all" on public.teams for update using (true) with check (true);

drop policy if exists "team_memberships_read_all" on public.team_memberships;
create policy "team_memberships_read_all" on public.team_memberships for select using (true);
drop policy if exists "team_memberships_write_all" on public.team_memberships;
create policy "team_memberships_write_all" on public.team_memberships for insert with check (true);
drop policy if exists "team_memberships_update_all" on public.team_memberships;
create policy "team_memberships_update_all" on public.team_memberships for update using (true) with check (true);

drop policy if exists "events_read_all" on public.events;
create policy "events_read_all" on public.events for select using (true);
drop policy if exists "events_write_all" on public.events;
create policy "events_write_all" on public.events for insert with check (true);
drop policy if exists "events_update_all" on public.events;
create policy "events_update_all" on public.events for update using (true) with check (true);

drop policy if exists "messages_read_all" on public.messages;
create policy "messages_read_all" on public.messages for select using (true);
drop policy if exists "messages_write_all" on public.messages;
create policy "messages_write_all" on public.messages for insert with check (true);
