-- EventScape (serverless) schema
-- This schema is intentionally permissive for demo usage.
-- For production, enable strict RLS and use Supabase Auth.

create extension if not exists "pgcrypto";

create table if not exists public.teams (
  name text primary key,
  color text not null default '#3b7eff',
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  team_name text not null references public.teams(name) on update cascade on delete restrict,
  members text not null default '',
  type text not null default 'Convention',
  field text not null default '',
  loc text not null default '',
  lat double precision not null,
  lng double precision not null,
  topic text not null default '',
  description text not null default '',
  scale text not null default '',
  files jsonb not null default '[]'::jsonb,
  feedbacks jsonb not null default '[]'::jsonb,
  liked_by text[] not null default '{}'::text[],
  created_at timestamptz not null default now()
);

create index if not exists events_team_name_idx on public.events(team_name);
create index if not exists events_created_at_idx on public.events(created_at desc);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  room text not null,
  sender_id text,
  sender_name text not null,
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists messages_room_created_at_idx on public.messages(room, created_at);

-- RLS (demo-friendly)
alter table public.teams enable row level security;
alter table public.events enable row level security;
alter table public.messages enable row level security;

drop policy if exists "teams_read_all" on public.teams;
create policy "teams_read_all" on public.teams for select using (true);
drop policy if exists "teams_write_all" on public.teams;
create policy "teams_write_all" on public.teams for insert with check (true);

drop policy if exists "events_read_all" on public.events;
create policy "events_read_all" on public.events for select using (true);
drop policy if exists "events_write_all" on public.events;
create policy "events_write_all" on public.events for insert with check (true);
drop policy if exists "events_update_all" on public.events;
create policy "events_update_all" on public.events for update using (true) with check (true);

drop policy if exists "messages_read_all" on public.messages;
create policy "messages_read_all" on public.messages for select using (true);
drop policy if exists "messages_write_all" on public.messages;
create policy "messages_write_all" on public.messages for insert with check (true);
